export const START_NOTIFICATION_COUNT = 'START_NOTIFICATION_COUNT'

export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT'
export const ADD_NOTIFICATION_COUNT = 'ADD_NOTIFICATION_COUNT'
export const SUB_NOTIFICATION_COUNT = 'SUB_NOTIFICATION_COUNT'
