stages:
  - install
  - deploy
install:
  stage: install
  script:
   - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then npm install; fi
  only:
    changes:
      - package.json
deploy:
  stage: deploy
  script:
   - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then cp -rf . /var/www/html/srm-frontend/; fi
